export const chatsMain = [
  {
    id: 1,
    title: "Jenil mangukiya",
    last_message: "Hii how are you!",
    last_message_time: "10:30 AM",
    unreadMessage: 2,
  },
  {
    id: 2,
    title: "Emma Watson",
    last_message: "Hey there!",
    last_message_time: "Yesterday",
    unreadMessage: 1,
    isGroup: false,
    totalMembers: 2,
  },
  {
    id: 3,
    title: "Work Group",
    last_message: "Meeting at 10 AM tomorrow.",
    last_message_time: "2 days ago",
    unreadMessage: 0,
    isGroup: true,
    totalMembers: 8,
  },
  {
    id: 4,
    title: "John Doe",
    last_message: "What's up?",
    last_message_time: "3 hours ago",
    unreadMessage: 3,
    isGroup: false,
    totalMembers: 2,
  },
  {
    id: 5,
    title: "Tech Enthusiasts",
    last_message: "New Raspberry Pi release!",
    last_message_time: "1 week ago",
    unreadMessage: 0,
    isGroup: true,
    totalMembers: 15,
  },
  {
    id: 6,
    title: "Sarah Johnson",
    last_message: "See you later!",
    last_message_time: "1 day ago",
    unreadMessage: 0,
    isGroup: false,
    totalMembers: 2,
  },
  {
    id: 7,
    title: "Family Chat",
    last_message: "Dinner tonight at 7 PM.",
    last_message_time: "Yesterday",
    unreadMessage: 0,
    isGroup: true,
    totalMembers: 6,
  },
  {
    id: 8,
    title: "Mike Tyson",
    last_message: "How have you been?",
    last_message_time: "2 days ago",
    unreadMessage: 5,
    isGroup: false,
    totalMembers: 2,
  },
  {
    id: 9,
    title: "Gaming Buddies",
    last_message: "New game released!",
    last_message_time: "4 days ago",
    unreadMessage: 0,
    isGroup: true,
    totalMembers: 10,
  },
  {
    id: 10,
    title: "Alex Rodriguez",
    last_message: "Did you watch the game last night?",
    last_message_time: "5 hours ago",
    unreadMessage: 0,
    isGroup: false,
    totalMembers: 2,
  },
  {
    id: 11,
    title: "Study Group",
    last_message: "Let's meet at the library.",
    last_message_time: "Yesterday",
    unreadMessage: 2,
    isGroup: true,
    totalMembers: 4,
  },
  {
    id: 12,
    title: "Jane Smith",
    last_message: "I'm on my way.",
    last_message_time: "6 hours ago",
    unreadMessage: 0,
    isGroup: false,
    totalMembers: 2,
  },
  {
    id: 13,
    title: "Fitness Club",
    last_message: "Workout session today at 5 PM.",
    last_message_time: "Today",
    unreadMessage: 0,
    isGroup: true,
    totalMembers: 12,
  },
  {
    id: 14,
    title: "Robert Downey Jr.",
    last_message: "Check out this meme!",
    last_message_time: "3 days ago",
    unreadMessage: 1,
    isGroup: false,
    totalMembers: 2,
  },
  {
    id: 15,
    title: "Photography Enthusiasts",
    last_message: "New photo editing software available.",
    last_message_time: "2 weeks ago",
    unreadMessage: 0,
    isGroup: true,
    totalMembers: 20,
  },
  {
    id: 16,
    title: "Emily Brown",
    last_message: "See you tomorrow!",
    last_message_time: "Yesterday",
    unreadMessage: 0,
    isGroup: false,
    totalMembers: 2,
  },
  {
    id: 17,
    title: "Book Club",
    last_message: "Next book: 'To Kill a Mockingbird'.",
    last_message_time: "3 days ago",
    unreadMessage: 0,
    isGroup: true,
    totalMembers: 7,
  },
  {
    id: 18,
    title: "Jack Sparrow",
    last_message: "Arrr matey!",
    last_message_time: "Yesterday",
    unreadMessage: 0,
    isGroup: false,
    totalMembers: 2,
  },
  {
    id: 19,
    title: "Travel Lovers",
    last_message: "Planning a trip to Europe!",
    last_message_time: "1 week ago",
    unreadMessage: 0,
    isGroup: true,
    totalMembers: 18,
  },
  {
    id: 20,
    title: "Harry Potter Fan Club",
    last_message: "Which house are you in?",
    last_message_time: "2 weeks ago",
    unreadMessage: 0,
    isGroup: true,
    totalMembers: 30,
  },
];
